# -*- coding: utf-8 -*-
"""Basic-python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/RatchaSun/8f5972058bfb071adea50d0480401359/basic-python.ipynb
"""

print('Hello World')

name = 'Sun'
# ชื่อ
money = 200000
# เงินในกระเป๋า
bank = 500000.25
# เงินในธนาคาร

print(name)

print('name' + str (money))

print(name, type (name))
print(money, type (money))
print(bank, type (bank))
# คำสั่ง type ใช้เชคประเภทตัวแปร

"""## print () แบบพิเศษ (.format)"""

name = 'Sun'
money = 20
bank = 500.25

print(name + 'มีเงินในกระเป๋า' + str (money) + 'มีเงินในธนาคาร'  + str (bank))
# แบบธรรมดา ไม่ควรใช้


print('{} มีเงินในกระเป๋า {:,d} บาท มีเงินในบัญชี {:,.3f} บาท'.format(name,money,bank))
# แบบที่ 1 .format (:,d = ใส่เครื่องหมาย ,) (:,.3f = ใสเครื่องหมาย . , ในทุก3หลัก)


print(f'{name} มีเงินในกระเป๋า {money:,d} บาท มีเงินในบัญชี {bank:,.0f} บาท')
# แบบที่ 2 f-string (:,d = ใส่เครื่องหมาย ,) (:,.0f = ใสเครื่องหมาย . ,)

print('%s มีเงินในกระเป๋า %d บาท มีเงินในบัญชี %f บาท'%(name,money,bank))
# แบบที่ 3 %s (string), %d (decimal integer), %f (floating point)

